github_actions:
- .github/**/*

crowdin:
- crowdin.yml

ecoscore:
- lang/en/texts/ecoscore/**/*
- lang/en/texts/eco-score-the-environmental-impact-of-food-products.html
- lang/en/texts/ecoscore-computation.html

presskit-ecoscore:
- lang/en/texts/presskit-ecoscore.html

nutriscore:
- lang/en/texts/nutriscore/**/*
- lang/en/texts/open-food-facts-and-the-nutriscore.html
- lang/en/texts/nutriscore-formula.html
- lang/en/texts/nutriscore.html
roadmap2019-roadmap:
- lang/en/texts/2019-roadmap.html
advanced-user-guide:
- lang/en/texts/advanced-user-guide.html
better-food-choices-for-a-better-health-lets-mobilize:
- lang/en/texts/better-food-choices-for-a-better-health-lets-mobilize.html
code-of-conduct:
- lang/en/texts/code-of-conduct.html
contact:
- lang/en/texts/contact.html
contacts:
- lang/en/texts/contacts.html
contribute-to-open-food-facts-by-playing:
- lang/en/texts/contribute-to-open-food-facts-by-playing.html
contribute:
- lang/en/texts/contribute.html
cop-26:
- lang/en/texts/cop26/**/*
data:
- lang/en/texts/data.html
dev-page:
- lang/en/texts/dev-android.html
- lang/en/texts/dev-artificial-intelligence.html
- lang/en/texts/dev-emerging.html
- lang/en/texts/dev-general.html
- lang/en/texts/dev-ios.html
- lang/en/texts/dev-server.html
- lang/en/texts/development.html
discover:
- lang/en/texts/discover.html
donate:
- lang/en/texts/donate.html
education:
- lang/en/texts/education.html
experimental-nutrition-score-france:
- lang/en/texts/experimental-nutrition-score-france.html
faq:
- lang/en/texts/faq.html
feuille-de-route-2012:
- lang/en/texts/feuille-de-route-2012.html
google-impact-challenge-on-climate:
- lang/en/texts/google-impact-challenge-on-climate.html
google-summer-of-code:
- lang/en/texts/google-summer-of-code.html
graphs-in-3-clicks:
- lang/en/texts/graphs-in-3-clicks.html
help-complete-products:
- lang/en/texts/help-complete-products.html
help-us-fill-up-on-fiber:
- lang/en/texts/help-us-fill-up-on-fiber.html
how-to-add-a-product:
- lang/en/texts/how-to-add-a-product.html
how-to-complete-products-on-android:
- lang/en/texts/how-to-complete-products-on-android.html
index-pro:
- lang/en/texts/index-pro.html
index:
- lang/en/texts/index.html
ingredient-detector:
- lang/en/texts/ingredient-detector.html
iphone:
- lang/en/texts/iphone.html
keyfacts:
- lang/en/texts/keyfacts.html
legal:
- lang/en/texts/legal.html
logo-obf:
- lang/en/texts/logo-obf.html
logo:
- lang/en/texts/logo.html
missions-texts:
- lang/en/texts/missions-texts.html
missions:
- lang/en/texts/missions.html
mobile-app-open-food-facts:
- lang/en/texts/mobile-app-open-food-facts.html
nova:
- lang/en/texts/nova.html
- lang/en/texts/processing/**/*
numbers-selected:
- lang/en/texts/numbers-selected.html
nutrients-list:
- lang/en/texts/nutrients-list.html
nutrition-score-france:
- lang/en/texts/nutrition-score-france.html
nutrition-score-uk:
- lang/en/texts/nutrition-score-uk.html
nutrition-traffic-lights:
- lang/en/texts/nutrition-traffic-lights.html
open-food-facts-vision-mission-values-and-programs:
- lang/en/texts/open-food-facts-vision-mission-values-and-programs.html
open-food-hunt-2015:
- lang/en/texts/open-food-hunt-2015.html
operation-sodas:
- lang/en/texts/operation-sodas.html
partners:
- lang/en/texts/partners.html
presentations:
- lang/en/texts/presentations.html
press-and-blogs:
- lang/en/texts/press-and-blogs.html
press-old:
- lang/en/texts/press-old.html
press:
- lang/en/texts/press.html
presskit_country_selection:
- lang/en/texts/presskit_de_CH_selection.html
- lang/en/texts/presskit_de_DE_selection.html
- lang/en/texts/presskit_en_AU_selection.html
- lang/en/texts/presskit_en_UK_selection.html
- lang/en/texts/presskit_es_ES_selection.html
- lang/en/texts/presskit_fr_BE_selection.html
- lang/en/texts/presskit_fr_CH_selection.html
- lang/en/texts/presskit_fr_FR_selection.html
- lang/en/texts/presskit_it_CH_selection.html
- lang/en/texts/presskit_it_IT_selection.html
- lang/en/texts/presskit_nl_BE_selection.html
- lang/en/texts/presskit_other_languages.html
- lang/en/texts/presskit_pt_BR_selection.html
- lang/en/texts/presskit_pt_PT_selection.html
- lang/en/texts/presskit_selection.html
- lang/en/texts/presskit_vi_VI_selection.html
producers:
- lang/en/texts/producers.html
product-preferences:
- lang/en/texts/product-preferences.html
products:
- lang/en/texts/products.html
rate-your-vending-machine:
- lang/en/texts/rateyourvendingmachine.html
scan-parties:
- lang/en/texts/scan-parties.html
science:
- lang/en/texts/science.html
sendinblue:
- lang/en/texts/sendinblue.html
Smoothie:
- lang/en/texts/smoothie/**/*
sugar:
- lang/en/texts/sugar.html
terms-of-use:
- lang/en/texts/terms-of-use.html
update-a-product-from-the-mobile-app:
- lang/en/texts/update-a-product-from-the-mobile-app.html
who-we-are:
- lang/en/texts/who-we-are.html
